service: autoping-test-lambda

frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  region: eu-central-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "*"

functions:
  getMessageList:
    handler: handler.getMessageList
    events:
      - http:
          path: messages
          method: get
          cors: true
  createMessage:
    handler: handler.createMessage
    events:
      - http:
          path: messages
          method: post
          cors: true

plugins:
  - serverless-offline
